"""initial tables

Revision ID: b39a8d911474
Revises: 
Create Date: 2026-05-31 03:23:47.249574
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39a8d911474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_station_id'), 'alerts', ['station_id'], unique=False)
    op.create_table('defect_summaries',
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('total_inspected', sa.Integer(), nullable=False),
    sa.Column('total_passed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('missing_component_count', sa.Integer(), nullable=False),
    sa.Column('qr_error_count', sa.Integer(), nullable=False),
    sa.Column('sn_error_count', sa.Integer(), nullable=False),
    sa.Column('antenna_error_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_summaries_station_id'), 'defect_summaries', ['station_id'], unique=False)
    op.create_index(op.f('ix_defect_summaries_summary_date'), 'defect_summaries', ['summary_date'], unique=False)
    op.create_table('inspections',
    sa.Column('product_serial', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('missing_components', sa.Text(), nullable=True),
    sa.Column('qr_result', sa.String(length=20), nullable=True),
    sa.Column('sn_result', sa.String(length=20), nullable=True),
    sa.Column('antenna_result', sa.String(length=20), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_batch_number'), 'inspections', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inspections_product_serial'), 'inspections', ['product_serial'], unique=False)
    op.create_index(op.f('ix_inspections_product_type'), 'inspections', ['product_type'], unique=False)
    op.create_index(op.f('ix_inspections_station_id'), 'inspections', ['station_id'], unique=False)
    op.create_table('product_templates',
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('required_components', sa.Text(), nullable=False),
    sa.Column('component_positions', sa.Text(), nullable=True),
    sa.Column('antenna_position', sa.Text(), nullable=True),
    sa.Column('sn_format', sa.String(length=200), nullable=True),
    sa.Column('qr_format', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_product_type'), 'product_templates', ['product_type'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_templates_product_type'), table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index(op.f('ix_inspections_station_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_product_type'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_product_serial'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_batch_number'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_defect_summaries_summary_date'), table_name='defect_summaries')
    op.drop_index(op.f('ix_defect_summaries_station_id'), table_name='defect_summaries')
    op.drop_table('defect_summaries')
    op.drop_index(op.f('ix_alerts_station_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
